# -*- coding: utf-8 -*-
"""hello.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Katiy9q16EDdDcxasP8S9qFV3RSOZN2V
"""

import streamlit as st
st.write('Hello world!')